Modded Leaderboard Patch
MaxWasUnavailable/LobbyCompatibility pull request #7
Opened 2024-01-11 02:15 UTC by Xilophor

Creates a separate modded leaderboard and modded challenge save file

2024-01-11 02:46 UTC, legoandmars commented
looks good, seems to work from my testing 

I might add a (Modded) or some other indication this is separate from the Vanilla challenge at the top text on the leaderboard menu
![image](https://github.com/MaxWasUnavailable/LobbyCompatibility/assets/34404266/9904d2f5-4ae5-4145-b1bc-88c97e05cb41)

2024-01-14 23:15 UTC, legoandmars commented
In `LobbyCompatibilityPlugin.GetAsyncInfo`, I would replace `(BindingsFlags)60` with `BindingFlags.Instance | BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic`, just so it's slightly clearer what it's doing

You might be able to just replace it with `BindingFlags.Instance | BindingFlags.NonPublic`

2024-01-25 14:37 UTC, MaxWasUnavailable commented
@Xilophor Needs merge conflict fixing

2024-01-25 19:20 UTC, MaxWasUnavailable requested changes

2024-01-25 19:20 UTC, MaxWasUnavailable commented on LobbyCompatibility/LobbyCompatibilityPlugin.cs
> +    public static MethodInfo? GetAsyncInfo(Type type, string method)
Can this be moved to a helper? E.g. "HarmonyHelper"?

2024-01-25 19:20 UTC, MaxWasUnavailable commented on LobbyCompatibility/Patches/ChallengeSaveFilePatch.cs
> +    [HarmonyPatch(typeof(ES3Settings), MethodType.Constructor, new Type[] { typeof(string), typeof(ES3Settings) })]
Explicit "new Type[]" isn't required

2024-01-25 19:20 UTC, MaxWasUnavailable commented on LobbyCompatibility/Patches/ChallengeSaveFilePatch.cs
> +        path = (path == "LCChallengeFile") ? "LCModdedChallengeFile" : path;
() isn't required here

2024-01-25 19:20 UTC, MaxWasUnavailable commented on LobbyCompatibility/Patches/LeaderboardNamePatch.cs
> +    [HarmonyPatch(typeof(ISteamUserStats), nameof(ISteamUserStats.FindOrCreateLeaderboard))]
For consistency with other patches, I'd probably rename the class to the harmony target class, and add [HarmonyPatch(...)] to the class, with the method HarmonyPatch to the method.

2024-02-01 19:47 UTC, MaxWasUnavailable approved these changes

2024-02-01 19:47 UTC, merged